/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package manufactura;

import Clases.DatosManufactura;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gzld6k
 */
public class CapturaManufactura extends javax.swing.JFrame {

    /**
     * Creates new form CapturaManufactura
     */
    
    Double totalHCDIR=0.0;
    Double totalHCIND=0.0;
    DatosManufactura dm;
    public CapturaManufactura(DatosManufactura DM){
        initComponents();
        dm=DM;
        lblEtiqueta.setText("CAD.:"+DM.Codigo.Cadena+" PLAT.:"+ DM.Codigo.Plataforma+ " COD:"+ DM.Codigo.Codigo+ " L:"+DM.Codigo.Linea +" T:"+DM.Codigo.Turno );
        hcDirLinea.setValue(Double.parseDouble( DM.HCDIRLINEA));
        hcDirSistemas.setValue(Double.parseDouble(DM.HCDIRSISTEMAS));
        HCDirLPS.setValue(Double.parseDouble(DM.HCDIRLPS));
        hcDirSop.setValue(Double.parseDouble(DM.HCDIRSOPORTE));
        hcDirConten.setValue(Double.parseDouble(DM.HCDIRCONTE));
        hcDIrFTQ.setValue(Double.parseDouble(DM.HCDIRFTQ));
        hcDirPilot.setValue(Double.parseDouble(DM.HCDIRPILOTOS));
        hcDirTabInsp.setValue(Double.parseDouble(DM.HCDIRTABINSP));
        hcIndRutas.setValue(Double.parseDouble(DM.HCINDRUTAS));
        hcRutasInt.setValue(Double.parseDouble(DM.HCRUTASINT));
        ptosPzasPond.setValue(Double.parseDouble(DM.PUNTOSPZAPOND));
        capUtilHta.setValue(Double.parseDouble(DM.CAP_UTIL_HTA));
        SalidaPieza.setValue(Double.parseDouble(DM.SalidaEnPieza));
        hcDirSopLPS.setValue(Double.parseDouble(DM.HCDIRSOPLPS));
        totalHCDIR=Double.parseDouble( DM.HCDIRLINEA)+Double.parseDouble(DM.HCDIRSISTEMAS)+Double.parseDouble(DM.HCDIRLPS)+Double.parseDouble(DM.HCDIRSOPORTE)+Double.parseDouble(DM.HCDIRCONTE)+Double.parseDouble(DM.HCDIRFTQ)+Double.parseDouble(DM.HCDIRSOPLPS);
        totalHCDIR+=Double.parseDouble(DM.HCDIRPILOTOS)+Double.parseDouble(DM.HCDIRTABINSP);
        totalHCIND=Double.parseDouble(DM.HCINDRUTAS);
        lblHCDIR.setText(totalHCDIR.toString());
        lblHCIND.setText(totalHCIND.toString());
         ObtenerHorasPagadas(DM.Codigo.Idcodigo);
    }
      public Double Regresa2Decimales(Double Valor)
    {
        try{
         int aux = (int)(Valor*100);//1243
            Valor = aux/100d;// 
        }catch(Exception e)
        {
            System.out.println(e.toString());
        }
        return Valor;
    }
    
    public void Sumar()
    {
        totalHCDIR=Double.parseDouble(HCDirLPS.getValue().toString())+Double.parseDouble(hcDirLinea.getValue().toString())+Double.parseDouble(hcDirSistemas.getValue().toString())+Double.parseDouble(hcDirSop.getValue().toString())+
         Double.parseDouble(hcDirConten.getValue().toString())   +Double.parseDouble(hcDIrFTQ.getValue().toString()) +Double.parseDouble(hcDirPilot.getValue().toString()) +Double.parseDouble(hcDirTabInsp.getValue().toString()) ;
        totalHCIND=Double.parseDouble(hcIndRutas.getValue().toString());
        lblHCDIR.setText(totalHCDIR.toString());
        lblHCIND.setText(totalHCIND.toString());
    }
    public void ObtenerHorasPagadas(String Idcodigo)
    {
        try{
             ResultSet rs=Principal.cn.GetConsulta("select manu.IDCODIGO, manu.CADENA, manu.LINEA,  ROUND((manu.horasemb),2) as horasemb, ROUND((manu.hrsPagadas),2) as hrsPagadas,  TRUNCATE(( manu.horasemb/manu.hrsPagadas)*100,2) as efic from \n" +
                "(select c.LINEA, c.CADENA, c.IDCODIGO, (m.PUNTOSPZAPOND*m.SALIDAENPIEZA/100) as horasemb,  IF(c.TURNO='A',(m.HCDIRLINEA*9),(m.HCDIRLINEA*7.9)) as hrsPagadas  from manufactura as m, codigos as c where m.idcodigo=c.IDCODIGO) as manu where manu.idcodigo="+Idcodigo);
             if(rs.next())
             {
                 lblHorasEmb.setText(Regresa2Decimales(rs.getDouble("horasemb")).toString());
                 lblHorasPag.setText(Regresa2Decimales( rs.getDouble("hrspagadas")).toString());
                 lblObjetivoManuf.setText(Regresa2Decimales( rs.getDouble("efic")).toString());
             }
        }catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HCDirLPS = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        hcDirSop = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        hcDirTabInsp = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        hcDirConten = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        hcDIrFTQ = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        hcDirPilot = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hcDirSistemas = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        hcIndRutas = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        ptosPzasPond = new javax.swing.JSpinner();
        hcDirLinea = new javax.swing.JSpinner();
        capUtilHta = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEntrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblHCDIR = new javax.swing.JLabel();
        lblHCIND = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblHorasEmb = new javax.swing.JLabel();
        lblHorasPag = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblObjetivoManuf = new javax.swing.JLabel();
        lblEtiqueta = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        SalidaPieza = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        hcDirSopLPS = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        hcRutasInt = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CAPTURA INFORMACION MANUFACTURA");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnlMenu.setBackground(new java.awt.Color(255, 255, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("MANUFACTURA");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.setBackground(new java.awt.Color(252, 246, 240));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("HC DIRECTO LINEA:");

        HCDirLPS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        HCDirLPS.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        HCDirLPS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                HCDirLPSStateChanged(evt);
            }
        });
        HCDirLPS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                HCDirLPSFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("HC DIRECTO LPS:");

        hcDirSop.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hcDirSop.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        hcDirSop.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hcDirSopStateChanged(evt);
            }
        });
        hcDirSop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hcDirSopFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("HC DIRECTO SOP.:");

        hcDirTabInsp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hcDirTabInsp.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        hcDirTabInsp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hcDirTabInspStateChanged(evt);
            }
        });
        hcDirTabInsp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hcDirTabInspFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("HC DIRECTO TAB. INSP.:");

        hcDirConten.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hcDirConten.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        hcDirConten.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hcDirContenStateChanged(evt);
            }
        });
        hcDirConten.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hcDirContenFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("HC DIRECTO CONTEN:");

        hcDIrFTQ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hcDIrFTQ.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        hcDIrFTQ.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hcDIrFTQStateChanged(evt);
            }
        });
        hcDIrFTQ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hcDIrFTQFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("HC DIRECTO FTQ:");

        hcDirPilot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hcDirPilot.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        hcDirPilot.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hcDirPilotStateChanged(evt);
            }
        });
        hcDirPilot.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hcDirPilotFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("HC DIRECTO PILOTOS:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("HC DIRECTO SISTEMAS:");

        hcDirSistemas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hcDirSistemas.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        hcDirSistemas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hcDirSistemasStateChanged(evt);
            }
        });
        hcDirSistemas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hcDirSistemasFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("HC IND. RUTAS:");

        hcIndRutas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hcIndRutas.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        hcIndRutas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hcIndRutasStateChanged(evt);
            }
        });
        hcIndRutas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hcIndRutasFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("PTOS. PIEZAS POND.:");

        ptosPzasPond.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ptosPzasPond.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        ptosPzasPond.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ptosPzasPondFocusLost(evt);
            }
        });

        hcDirLinea.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hcDirLinea.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        hcDirLinea.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hcDirLineaStateChanged(evt);
            }
        });
        hcDirLinea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hcDirLineaFocusLost(evt);
            }
        });
        hcDirLinea.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                hcDirLineaVetoableChange(evt);
            }
        });

        capUtilHta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        capUtilHta.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("% CAP. ACTUAL:");

        jPanel2.setBackground(new java.awt.Color(250, 238, 5));

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image55.png"))); // NOI18N
        btnEntrar.setText("GUARDAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/navigate-left48.png"))); // NOI18N
        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("NUMERO HC DIRECTAS:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("NUMERO HC INDIRECTAS:");

        lblHCDIR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHCDIR.setForeground(new java.awt.Color(51, 51, 51));
        lblHCDIR.setText("0");
        lblHCDIR.setPreferredSize(new java.awt.Dimension(13, 50));

        lblHCIND.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHCIND.setForeground(new java.awt.Color(51, 51, 51));
        lblHCIND.setText("0");
        lblHCIND.setPreferredSize(new java.awt.Dimension(13, 50));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("HORAS EMB.:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("HORAS PAGADAS:");

        lblHorasEmb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHorasEmb.setForeground(new java.awt.Color(51, 51, 51));
        lblHorasEmb.setText("0");
        lblHorasEmb.setPreferredSize(new java.awt.Dimension(13, 50));

        lblHorasPag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHorasPag.setForeground(new java.awt.Color(51, 51, 51));
        lblHorasPag.setText("0");
        lblHorasPag.setPreferredSize(new java.awt.Dimension(13, 50));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("OBJETIVO MANUF.:");

        lblObjetivoManuf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblObjetivoManuf.setForeground(new java.awt.Color(51, 51, 51));
        lblObjetivoManuf.setText("0");
        lblObjetivoManuf.setPreferredSize(new java.awt.Dimension(13, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHCIND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHCDIR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHorasPag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHorasEmb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblObjetivoManuf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblHCDIR, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblHCIND, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lblHorasEmb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(lblHorasPag, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(lblObjetivoManuf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnEntrar)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblEtiqueta.setBackground(new java.awt.Color(51, 51, 51));
        lblEtiqueta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEtiqueta.setText("..");
        lblEtiqueta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 255));
        jLabel15.setText("SALIDAS EN PIEZA:");

        SalidaPieza.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SalidaPieza.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setText("HC DIRECTO SOP. LPS.:");

        hcDirSopLPS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hcDirSopLPS.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        hcDirSopLPS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hcDirSopLPSStateChanged(evt);
            }
        });
        hcDirSopLPS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hcDirSopLPSFocusLost(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("HC RUTAS INT.:");

        hcRutasInt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hcRutasInt.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        hcRutasInt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hcRutasIntStateChanged(evt);
            }
        });
        hcRutasInt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hcRutasIntFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEtiqueta)
                .addContainerGap(983, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(hcDIrFTQ, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(hcDirConten, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(hcDirLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(HCDirLPS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(hcDirSopLPS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(hcDirSop, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(hcDirTabInsp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(hcDirSistemas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(hcDirPilot, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(hcIndRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(ptosPzasPond, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(capUtilHta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(SalidaPieza, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(hcRutasInt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblEtiqueta)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(hcDirLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HCDirLPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hcDirSop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(hcDirSopLPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(hcDirTabInsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(hcDirConten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(hcDIrFTQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(hcDirPilot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(hcDirSistemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(hcIndRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(hcRutasInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ptosPzasPond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(capUtilHta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(SalidaPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showConfirmDialog(null, "", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if((JOptionPane.showConfirmDialog(null, "Esta seguro que desea actualizar?", "Confirmar", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION))
        {
            ArrayList<String> listaInsert=new ArrayList<String>();
            listaInsert.add(hcDirLinea.getValue().toString());
            listaInsert.add(HCDirLPS.getValue().toString());
            listaInsert.add(hcDirSop.getValue().toString());
            listaInsert.add(hcDirTabInsp.getValue().toString());
            listaInsert.add(hcDirConten.getValue().toString());
            listaInsert.add(hcDIrFTQ.getValue().toString());
            listaInsert.add(hcDirPilot.getValue().toString());
            listaInsert.add(hcDirSistemas.getValue().toString());
            listaInsert.add(hcIndRutas.getValue().toString());
            listaInsert.add(hcRutasInt.getValue().toString());
            listaInsert.add(ptosPzasPond.getValue().toString());
            listaInsert.add(capUtilHta.getValue().toString());
            listaInsert.add(SalidaPieza.getValue().toString());
            listaInsert.add(hcDirSopLPS.getValue().toString());
            listaInsert.add(Principal.UsuarioLogeado.codigo);
            listaInsert.add(dm.Codigo.Idcodigo);
           if( Principal.cn.EjecutarInsert("update  MANUFACTURA SET HCDIRLINEA=?, HCDIRLPS=?, HCDIRSOPORTE=?, HCDIRTABINSP=?, HCDIRCONTE=?, HCDIRFTQ=?, HCDIRPILOTOS=?, HCDIRSISTEMAS=?, HCINDRUTAS=?, hcrutasint=?, PUNTOSPZAPOND=?, CAP_UTIL_HTA=?, salidaenpieza=?, HCDIRSOPLPS=?, USUARIOMODIF=?  WHERE IDCODIGO=?", listaInsert))
           {
             //  JOptionPane.showMessageDialog(null, "Datos Actualizados", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
               this.dispose();
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Error, al guardar", "Confirmacion", JOptionPane.WARNING_MESSAGE);
           }
           
        }

    }//GEN-LAST:event_btnEntrarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        SelectCodigo p=new SelectCodigo();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void hcDirLineaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_hcDirLineaVetoableChange
        // TODO add your handling code here:
        if(Double.parseDouble( hcDirLinea.getValue().toString())<0)
        {
         hcDirLinea.setValue(0);
        }
    }//GEN-LAST:event_hcDirLineaVetoableChange

    private void hcDirLineaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hcDirLineaFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hcDirLineaFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void HCDirLPSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HCDirLPSFocusLost
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_HCDirLPSFocusLost

    private void hcDirSopFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hcDirSopFocusLost
        // TODO add your handling code here:    
        Sumar();
    }//GEN-LAST:event_hcDirSopFocusLost

    private void hcDirTabInspFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hcDirTabInspFocusLost
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcDirTabInspFocusLost

    private void hcDirContenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hcDirContenFocusLost
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcDirContenFocusLost

    private void hcDIrFTQFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hcDIrFTQFocusLost
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcDIrFTQFocusLost

    private void hcDirPilotFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hcDirPilotFocusLost
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcDirPilotFocusLost

    private void hcDirSistemasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hcDirSistemasFocusLost
        Sumar();        // TODO add your handling code here:
    }//GEN-LAST:event_hcDirSistemasFocusLost

    private void hcIndRutasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hcIndRutasFocusLost
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcIndRutasFocusLost

    private void ptosPzasPondFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ptosPzasPondFocusLost
        // TODO add your handling code here:
       Sumar();
    }//GEN-LAST:event_ptosPzasPondFocusLost

    private void HCDirLPSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_HCDirLPSStateChanged
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_HCDirLPSStateChanged

    private void hcDirSopStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hcDirSopStateChanged
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcDirSopStateChanged

    private void hcDirLineaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hcDirLineaStateChanged
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcDirLineaStateChanged

    private void hcDirTabInspStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hcDirTabInspStateChanged
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcDirTabInspStateChanged

    private void hcDirContenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hcDirContenStateChanged
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcDirContenStateChanged

    private void hcDIrFTQStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hcDIrFTQStateChanged
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcDIrFTQStateChanged

    private void hcDirPilotStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hcDirPilotStateChanged
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcDirPilotStateChanged

    private void hcDirSistemasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hcDirSistemasStateChanged
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcDirSistemasStateChanged

    private void hcIndRutasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hcIndRutasStateChanged
        // TODO add your handling code here:
        Sumar();
    }//GEN-LAST:event_hcIndRutasStateChanged

    private void hcDirSopLPSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hcDirSopLPSStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_hcDirSopLPSStateChanged

    private void hcDirSopLPSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hcDirSopLPSFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_hcDirSopLPSFocusLost

    private void hcRutasIntStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hcRutasIntStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_hcRutasIntStateChanged

    private void hcRutasIntFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hcRutasIntFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_hcRutasIntFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapturaManufactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapturaManufactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapturaManufactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapturaManufactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapturaManufactura(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner HCDirLPS;
    private javax.swing.JSpinner SalidaPieza;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JSpinner capUtilHta;
    private javax.swing.JSpinner hcDIrFTQ;
    private javax.swing.JSpinner hcDirConten;
    private javax.swing.JSpinner hcDirLinea;
    private javax.swing.JSpinner hcDirPilot;
    private javax.swing.JSpinner hcDirSistemas;
    private javax.swing.JSpinner hcDirSop;
    private javax.swing.JSpinner hcDirSopLPS;
    private javax.swing.JSpinner hcDirTabInsp;
    private javax.swing.JSpinner hcIndRutas;
    private javax.swing.JSpinner hcRutasInt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEtiqueta;
    private javax.swing.JLabel lblHCDIR;
    private javax.swing.JLabel lblHCIND;
    private javax.swing.JLabel lblHorasEmb;
    private javax.swing.JLabel lblHorasPag;
    private javax.swing.JLabel lblObjetivoManuf;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JSpinner ptosPzasPond;
    // End of variables declaration//GEN-END:variables
}
