/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package manufactura;

import java.awt.Image;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gzld6k
 */
public class DetalleEficiencia extends javax.swing.JFrame {

    /**
     * Creates new form DetalleEficiencia
     */
    DefaultTableModel modelo;
    public DetalleEficiencia(String Cadena) {
        initComponents();
        lblCadena.setText(lblCadena.getText()+ Cadena);
        Image icon = new ImageIcon(getClass().getResource("/Images/competitors-icon.png")).getImage();
            setIconImage(icon);
        EnlazarDgvA(Cadena);
        EnlazarDgvB(Cadena);
    }
    
    public void EnlazarDgvA(String Cadena)
    {
        try {
          modelo =new DefaultTableModel(){
          @Override
           public boolean isCellEditable(int row, int column) {
                     //all cells false
                return false;
              }
          };
         modelo.setColumnIdentifiers(new Object[]{"IDENT", "LINEA", "CODIGO", "SALIDA", "HCDIR", "PUNTOS.PZA",  "HRSEMB", "HRSPAGADAS", "EFIC.MANUF."});
         String query="select manu.idcodigo, manu.CADENA, manu.CODIGO, manu.LINEA, manu.turno, manu.SALIDAENPIEZA AS 'SALIDA', manu.hc as 'HCDIR',  Manu.PUNTOSPZAPOND AS 'PUNTOSPIEZA', ROUND(manu.horasemb) as 'HRSEMB', ROUND(manu.hrsPagadas) AS 'HRSPAG', TRUNCATE((manu.horasemb/manu.hrsPagadas*100),2) AS EFIC  FROM"+
                 "(select c.IDCODIGO, c.LINEA,   c.CADENA, c.turno, c.codigo, m.HCDIRLINEA as hc, m.SALIDAENPIEZA, m.PUNTOSPZAPOND,  (m.PUNTOSPZAPOND*m.SALIDAENPIEZA/100) as horasemb,  IF(c.TURNO='A',(m.HCDIRLINEA*9),(m.HCDIRLINEA*7.9)) as hrsPagadas  from manufactura as m, codigos as c where m.idcodigo=c.IDCODIGO ) as manu, codigos as c "+
                   "where manu.IDCODIGO=c.IDCODIGO AND MANU.CADENA='"+Cadena+"' AND manu.TURNO='A'";
         tblTurnoA.setModel(modelo);  
         tblTurnoA.setModel(modelo); 
         ResultSet  rs=Principal.cn.GetConsulta(query);
            while(rs.next())
            {
               modelo.addRow(new Object[]{rs.getString("idcodigo"), rs.getString("linea"), rs.getString("codigo"), rs.getString("SALIDA"),  rs.getString("hcdir"), rs.getString("puntospieza"), rs.getString("hrsemb"), rs.getString("hrspag"), rs.getString("EFIC")});
            }
          
        }catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }
    public void EnlazarDgvB(String Cadena)
    {
        try {
             modelo =new DefaultTableModel(){ 
          @Override
           public boolean isCellEditable(int row, int column) {
                     //all cells false
                return true;
              }
            };
         modelo.setColumnIdentifiers(new Object[]{"IDENT", "LINEA", "CODIGO", "SALIDA", "HCDIR", "PUNTOS.PZA",  "HRSEMB", "HRSPAGADAS", "EFIC.MANUF."});
         String query="select manu.idcodigo,  manu.CADENA, manu.CODIGO, manu.LINEA, manu.turno, Manu.SALIDAENPIEZA AS 'SALIDA', manu.hc as 'HCDIR',  Manu.PUNTOSPZAPOND AS 'PUNTOSPIEZA', ROUND(manu.horasemb) as 'HRSEMB', ROUND(manu.hrsPagadas) AS 'HRSPAG', TRUNCATE((manu.horasemb/manu.hrsPagadas*100),2) AS EFIC  FROM"+
                 "(select c.IDCODIGO, c.LINEA,   c.CADENA, c.turno, c.codigo, m.HCDIRLINEA as hc, m.SALIDAENPIEZA, m.PUNTOSPZAPOND,  (m.PUNTOSPZAPOND*m.SALIDAENPIEZA/100) as horasemb,  IF(c.TURNO='A',(m.HCDIRLINEA*9),(m.HCDIRLINEA*7.9)) as hrsPagadas  from manufactura as m, codigos as c where m.idcodigo=c.IDCODIGO ) as manu, codigos as c " +
                   "where manu.IDCODIGO=c.IDCODIGO AND MANU.CADENA='"+Cadena+"' and manu.turno='B'";

            ResultSet  rs=Principal.cn.GetConsulta(query);
          while(rs.next())
            {
               modelo.addRow(new Object[]{rs.getString("idcodigo"), rs.getString("linea"), rs.getString("codigo"), rs.getString("SALIDA"),  rs.getString("hcdir"), rs.getString("puntospieza"), rs.getString("hrsemb"), rs.getString("hrspag"), rs.getString("EFIC")});
            }
           tblTurnoB.setModel(modelo);
        }catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCadena = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTurnoB = new Compille.RXTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTurnoA = new Compille.RXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DETALLE DE CADENA ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("TURNO B:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("TURNO A:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 64, -1, -1));

        lblCadena.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCadena.setForeground(new java.awt.Color(0, 0, 255));
        lblCadena.setText("Cadena:");
        getContentPane().add(lblCadena, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 0, -1, -1));

        tblTurnoB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTurnoB.setSelectAllForEdit(true);
        tblTurnoB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTurnoBMouseClicked(evt);
            }
        });
        tblTurnoB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblTurnoBPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblTurnoB);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 730, 498));

        tblTurnoA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTurnoA.setSelectAllForEdit(true);
        tblTurnoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTurnoAMouseClicked(evt);
            }
        });
        tblTurnoA.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblTurnoAPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tblTurnoA);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 730, 498));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTurnoBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTurnoBMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblTurnoBMouseClicked

    private void tblTurnoBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblTurnoBPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTurnoBPropertyChange

    private void tblTurnoAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTurnoAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTurnoAMouseClicked

    private void tblTurnoAPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblTurnoAPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTurnoAPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleEficiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleEficiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleEficiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleEficiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleEficiencia(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCadena;
    private Compille.RXTable tblTurnoA;
    private Compille.RXTable tblTurnoB;
    // End of variables declaration//GEN-END:variables
}
