/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package manufactura;

import Clases.Conection;
import Reportes.MenuReportes;
import Reportes.ReporteDistGente;
import java.awt.Image;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**

 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
   public static Conection cn;
   public static Clases.Usuario UsuarioLogeado;
    public Principal(Clases.Usuario u) {
       try {
            initComponents();
            cn=new Conection();
            UsuarioLogeado=u;
           //  btnPerfil.setIcon(UsuarioLogeado.Foto);
            txtEstado.setText("        Nombre: "+ UsuarioLogeado.nombre+ "           Puesto: "+ UsuarioLogeado.puesto+ "              Turno: "+UsuarioLogeado.turno+ "          Fecha: ");
            txtEstado.setEditable(false);
            Image icon = new ImageIcon(getClass().getResource("/Images/competitors-icon.png")).getImage();
            setIconImage(icon);
       } catch (Exception ex) {
           System.out.println(ex.toString());
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnUsuarios1 = new javax.swing.JButton();
        btnInformacion1 = new javax.swing.JButton();
        btnInformacion2 = new javax.swing.JButton();
        btnManufacturaExcel = new javax.swing.JButton();
        btnManufacturaExcel1 = new javax.swing.JButton();
        btnManufacturaExcel2 = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnContigencias = new javax.swing.JButton();
        btnExtrasGerencia = new javax.swing.JButton();
        btnReportes1 = new javax.swing.JButton();
        pnlPrincipal = new javax.swing.JPanel();
        txtEstado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MANUFACTURA ");
        setFocusCycleRoot(false);
        setResizable(false);
        setState(2);

        pnlMenu.setBackground(new java.awt.Color(255, 255, 153));

        btnUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        btnUsuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image42.png"))); // NOI18N
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnUsuarios1.setBackground(new java.awt.Color(204, 204, 204));
        btnUsuarios1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUsuarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/content-tree48.png"))); // NOI18N
        btnUsuarios1.setText("ALTAS");
        btnUsuarios1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsuarios1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios1.setVerifyInputWhenFocusTarget(false);
        btnUsuarios1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarios1ActionPerformed(evt);
            }
        });

        btnInformacion1.setBackground(new java.awt.Color(204, 204, 204));
        btnInformacion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInformacion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xlsx-win-icon.png"))); // NOI18N
        btnInformacion1.setText("CAPTURA GSD");
        btnInformacion1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInformacion1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInformacion1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInformacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacion1ActionPerformed(evt);
            }
        });

        btnInformacion2.setBackground(new java.awt.Color(204, 204, 204));
        btnInformacion2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInformacion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/billboard48.png"))); // NOI18N
        btnInformacion2.setText("CAPTURA MSD");
        btnInformacion2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInformacion2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInformacion2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInformacion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacion2ActionPerformed(evt);
            }
        });

        btnManufacturaExcel.setBackground(new java.awt.Color(204, 204, 204));
        btnManufacturaExcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnManufacturaExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/themes48.png"))); // NOI18N
        btnManufacturaExcel.setText("CAPTURA MANUF.");
        btnManufacturaExcel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManufacturaExcel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnManufacturaExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManufacturaExcel.setPreferredSize(new java.awt.Dimension(97, 75));
        btnManufacturaExcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManufacturaExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturaExcelActionPerformed(evt);
            }
        });

        btnManufacturaExcel1.setBackground(new java.awt.Color(204, 204, 204));
        btnManufacturaExcel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnManufacturaExcel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/objects-icon.png"))); // NOI18N
        btnManufacturaExcel1.setText("CAPTURA 1x1");
        btnManufacturaExcel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManufacturaExcel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManufacturaExcel1.setPreferredSize(new java.awt.Dimension(97, 75));
        btnManufacturaExcel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManufacturaExcel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturaExcel1ActionPerformed(evt);
            }
        });

        btnManufacturaExcel2.setBackground(new java.awt.Color(204, 204, 204));
        btnManufacturaExcel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnManufacturaExcel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maintenance48.png"))); // NOI18N
        btnManufacturaExcel2.setText("CAPTURA CORTE");
        btnManufacturaExcel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManufacturaExcel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManufacturaExcel2.setPreferredSize(new java.awt.Dimension(97, 75));
        btnManufacturaExcel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManufacturaExcel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturaExcel2ActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(204, 204, 204));
        btnReportes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/objects-icon.png"))); // NOI18N
        btnReportes.setText("REPORTES");
        btnReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setPreferredSize(new java.awt.Dimension(97, 75));
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnPerfil.setBackground(new java.awt.Color(204, 204, 204));
        btnPerfil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tester-icon.png"))); // NOI18N
        btnPerfil.setText("PERFIL");
        btnPerfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPerfil.setPreferredSize(new java.awt.Dimension(97, 75));
        btnPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnContigencias.setBackground(new java.awt.Color(204, 204, 204));
        btnContigencias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnContigencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cloud-sun-icon.png"))); // NOI18N
        btnContigencias.setText("CONT.");
        btnContigencias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnContigencias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContigencias.setPreferredSize(new java.awt.Dimension(97, 75));
        btnContigencias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContigencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContigenciasActionPerformed(evt);
            }
        });

        btnExtrasGerencia.setBackground(new java.awt.Color(204, 204, 204));
        btnExtrasGerencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExtrasGerencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Brief-case-icon.png"))); // NOI18N
        btnExtrasGerencia.setText("EXTRAS CIA.");
        btnExtrasGerencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExtrasGerencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExtrasGerencia.setPreferredSize(new java.awt.Dimension(97, 75));
        btnExtrasGerencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExtrasGerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtrasGerenciaActionPerformed(evt);
            }
        });

        btnReportes1.setBackground(new java.awt.Color(204, 204, 204));
        btnReportes1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReportes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/detalle.png"))); // NOI18N
        btnReportes1.setText("DET. MANUF.");
        btnReportes1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReportes1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes1.setPreferredSize(new java.awt.Dimension(97, 75));
        btnReportes1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInformacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInformacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManufacturaExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManufacturaExcel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManufacturaExcel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContigencias, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExtrasGerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addComponent(btnExtrasGerencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManufacturaExcel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManufacturaExcel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPerfil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnInformacion2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnContigencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManufacturaExcel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInformacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pnlPrincipal.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/slide29.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1100, 720));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cambios anteriores");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 1401, Short.MAX_VALUE)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel2))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        if(Principal.UsuarioLogeado.turno.equals("TODOS"))
        {
        CAPTURAINFORMACION F=new CAPTURAINFORMACION();
        this.setVisible(false);
        F.setLocationRelativeTo(null);
        F.setVisible(true);
        }
          else
             JOptionPane.showMessageDialog(this, "No tiene permisos para accesar a este modulo...", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnInformacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacion1ActionPerformed
        // TODO add your handling code here:
         if(Principal.UsuarioLogeado.turno.equals("TODOS"))
        {
        CapturaExcelGSD cEG=new CapturaExcelGSD();
        cEG.setLocationRelativeTo(null);
        cEG.setVisible(true);
        this.setVisible(false);
        }
         else
             JOptionPane.showMessageDialog(this, "No tiene permisos para accesar a este modulo...", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnInformacion1ActionPerformed

    private void btnInformacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacion2ActionPerformed
        // TODO add your handling code here:
         if(Principal.UsuarioLogeado.turno.equals("TODOS"))
        {
         CapturaExcelMSD cEG=new CapturaExcelMSD();
        cEG.setLocationRelativeTo(null);
        cEG.setVisible(true);
        this.setVisible(false);
        }
           else
             JOptionPane.showMessageDialog(this, "No tiene permisos para accesar a este modulo...", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnInformacion2ActionPerformed

    private void btnManufacturaExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturaExcelActionPerformed
        // TODO add your handling code here:
//        CapturaExcelManufactura cEG=new CapturaExcelManufactura();
        MenuManufactura cEG=new MenuManufactura();
        cEG.setLocationRelativeTo(null);
        cEG.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnManufacturaExcelActionPerformed

    private void btnUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarios1ActionPerformed
        // TODO add your handling code here:
//         if(Principal.UsuarioLogeado.turno.equals("TODOS"))
//        {
            CapturaCodigos cEG=new CapturaCodigos();
            cEG.setLocationRelativeTo(null);
            cEG.setVisible(true);
            this.setVisible(false);
//        }
//           else
//             JOptionPane.showMessageDialog(this, "No tiene permisos para accesar a este modulo...", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnUsuarios1ActionPerformed

    private void btnManufacturaExcel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturaExcel1ActionPerformed
        // TODO add your handling code here:
        SelectCodigo SC=new  SelectCodigo();
        this.dispose();
        SC.setLocationRelativeTo(null);
        SC.setVisible(true);
    }//GEN-LAST:event_btnManufacturaExcel1ActionPerformed

    private void btnManufacturaExcel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturaExcel2ActionPerformed
                // TODO add your handling code here:
                 Object[] possPlanta = {"MOCHIS", "GML"};
                    String OpcionPlanta = (String) JOptionPane.showInputDialog(
                            null,
                            "¿QUE PLANTA DESEA MODIFICAR?\n",
                            "CORTE",
                            JOptionPane.PLAIN_MESSAGE,
                            null,
                            possPlanta,
                          " ");
         Object[] possibilities = {"A", "B", "C","AC","BC"};
                    String s = (String) JOptionPane.showInputDialog(
                            null,
                            "¿QUE TURNO DESEA  MODIFICAR?\n",
                            "CORTE",
                            JOptionPane.PLAIN_MESSAGE,
                            null,
                            possibilities,
                          " ");
                    
        if(s!=null)            
        {
            CapturaGenteCorte eFP=new CapturaGenteCorte(OpcionPlanta,s);
            eFP.setLocationRelativeTo(null);
            this.hide();
            eFP.setVisible(true);
        }
//else
//        {
//            JOptionPane.showMessageDialog(null, "Seleccione un turno por favor", "Error", JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_btnManufacturaExcel2ActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        Reportes.MenuReportes rsp=new MenuReportes();
        rsp.setVisible(true);
        this.hide();
        rsp.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        DatosPersonales dt=new DatosPersonales(Principal.UsuarioLogeado);
        dt.setLocation(btnPerfil.getLocation().x- (dt.getSize().width-100), btnPerfil.getLocation().y-(dt.getSize().height-400));
        dt.setVisible(true);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnContigenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContigenciasActionPerformed
        // TODO add your handling code here:
        this.hide();
        CapturaContigencias CConti=new CapturaContigencias();
        CConti.setLocationRelativeTo(null);
        CConti.setVisible(true);
    }//GEN-LAST:event_btnContigenciasActionPerformed

    private void btnExtrasGerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtrasGerenciaActionPerformed
        // TODO add your handling code here:
         Object[] possPlanta = {"MOCHIS", "GML"};
                    String OpcionPlanta = (String) JOptionPane.showInputDialog(
                            null,
                            "¿QUE PLANTA DESEA MODIFICAR?\n",
                            "CORTE",
                            JOptionPane.PLAIN_MESSAGE,
                            null,
                            possPlanta,
                          " ");
        this.hide();
        Kachirules CConti=new Kachirules(OpcionPlanta);
        CConti.setLocationRelativeTo(null);
        CConti.setVisible(true);
    }//GEN-LAST:event_btnExtrasGerenciaActionPerformed

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        // TODO add your handling code here:
        CapturaImpactos CI=new  CapturaImpactos();
        CI.setVisible(true);
        CI.setLocationRelativeTo(null);
                
    }//GEN-LAST:event_jTextArea1MouseClicked

    private void btnReportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes1ActionPerformed
        // TODO add your handling code here:
        CapturaDetalladaConv SC=new  CapturaDetalladaConv();
        this.dispose();
        SC.setLocationRelativeTo(null);
        SC.setVisible(true);
    }//GEN-LAST:event_btnReportes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContigencias;
    private javax.swing.JButton btnExtrasGerencia;
    private javax.swing.JButton btnInformacion1;
    private javax.swing.JButton btnInformacion2;
    private javax.swing.JButton btnManufacturaExcel;
    private javax.swing.JButton btnManufacturaExcel1;
    private javax.swing.JButton btnManufacturaExcel2;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnReportes1;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnUsuarios1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtEstado;
    // End of variables declaration//GEN-END:variables
}
