/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import CapturasEffort.MenuEffort;
import effortGUA.MenuEffort2;
import Clases.DatosManufactura;
import java.awt.Image;
import javax.swing.ImageIcon;
import manufactura.CapturaExcelGSD_Verdadero;
import manufactura.Principal;
import manufactura.ReporteGSDVSActual;

/**
 *
 * @author gzld6k
 */
public class MenuReportes extends javax.swing.JFrame {

    /**
     * Creates new form MenuReportes
     */
    public MenuReportes() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/Images/competitors-icon.png")).getImage();
        setIconImage(icon);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDesgloseCorte = new javax.swing.JButton();
        btnDistGente = new javax.swing.JButton();
        btnRPR = new javax.swing.JButton();
        btnReporteHC = new javax.swing.JButton();
        btnEffort = new javax.swing.JButton();
        btnHC = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        GUAMUCHIL = new javax.swing.JLabel();
        btnRPR1 = new javax.swing.JButton();
        btnRPR2 = new javax.swing.JButton();
        btnAnalisisGente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDesgloseCorte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDesgloseCorte.setText("DESGLOSE GENTE CORTE");
        btnDesgloseCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesgloseCorteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesgloseCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 190, 80));

        btnDistGente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDistGente.setText("DIST. GENTE");
        btnDistGente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistGenteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDistGente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, 80));

        btnRPR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRPR.setText("RPR  LM & GUA");
        btnRPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRPRActionPerformed(evt);
            }
        });
        jPanel1.add(btnRPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 140, 80));

        btnReporteHC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReporteHC.setText("REPORTE HC ");
        btnReporteHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteHCActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporteHC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 190, 80));

        btnEffort.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEffort.setText("EFFORT LOS MOCHIS");
        btnEffort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffortActionPerformed(evt);
            }
        });
        jPanel1.add(btnEffort, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 190, 80));

        btnHC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHC.setText("HC CONCEPTO");
        btnHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHCActionPerformed(evt);
            }
        });
        jPanel1.add(btnHC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, 80));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("EFFORT GUAMUCHIL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 190, 80));

        GUAMUCHIL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        GUAMUCHIL.setText("REPORTES");
        jPanel1.add(GUAMUCHIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        btnRPR1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRPR1.setText("RPR MOCHIS");
        btnRPR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRPR1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRPR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 140, 80));

        btnRPR2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRPR2.setText("RPR GUAMUCHIL");
        btnRPR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRPR2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRPR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 140, 80));

        btnAnalisisGente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAnalisisGente.setText("GCSD VS Actual Report");
        btnAnalisisGente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisisGenteActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnalisisGente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 190, 80));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("GCSD VERDADERO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 190, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesgloseCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesgloseCorteActionPerformed
        // TODO add your handling code here:
        DesgloseCorte ds=new DesgloseCorte();
        ds.setLocationRelativeTo(null);
        ds.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_btnDesgloseCorteActionPerformed

    private void btnDistGenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistGenteActionPerformed
        // TODO add your handling code here:
        ReporteDistGente ds=new ReporteDistGente();
        ds.setLocationRelativeTo(null);
        ds.setVisible(true);
       this.hide();
    }//GEN-LAST:event_btnDistGenteActionPerformed

    private void btnRPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRPRActionPerformed
        // TODO add your handling code here:
       this.hide();
        RPR r=new RPR();
        r.setLocationRelativeTo(null);
        r.setVisible(true);
    }//GEN-LAST:event_btnRPRActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
           Principal p=new Principal(Principal.UsuarioLogeado);
           p.setLocationRelativeTo(null);
           p.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnReporteHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteHCActionPerformed
        // TODO add your handling code here:
        this.hide();
        DistGenteHC hc=new DistGenteHC();
        hc.setLocationRelativeTo(null);
        hc.setVisible(true);
    }//GEN-LAST:event_btnReporteHCActionPerformed

    private void btnEffortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffortActionPerformed
        // TODO add your handling code here:
        MenuEffort mE=new MenuEffort();
        mE.setVisible(true);
        this.hide();
     
    }//GEN-LAST:event_btnEffortActionPerformed

    private void btnHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHCActionPerformed
        DatosManufactura dm=new DatosManufactura();
        dm.REPORTEPORPLATAFORMAS();// TODO add your handling code here:
    }//GEN-LAST:event_btnHCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         MenuEffort2 mEe=new MenuEffort2();
        mEe.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRPR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRPR1ActionPerformed
        // TODO add your handling code here:
         this.hide();
        RPR_mochis r=new RPR_mochis();
        r.setLocationRelativeTo(null);
        r.setVisible(true);
    }//GEN-LAST:event_btnRPR1ActionPerformed

    private void btnRPR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRPR2ActionPerformed
        // TODO add your handling code here:
        
          this.hide();
        RPR_Gua r=new RPR_Gua();
        r.setLocationRelativeTo(null);
        r.setVisible(true);
        
    }//GEN-LAST:event_btnRPR2ActionPerformed

    private void btnAnalisisGenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisisGenteActionPerformed
        // TODO add your handling code here:
//            this.hide();
        ReporteGSDVSActual hc=new ReporteGSDVSActual();
        //hc.setLocationRelativeTo(null);
       // hc.setVisible(true);
    }//GEN-LAST:event_btnAnalisisGenteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        manufactura.CapturaExcelGSD_Verdadero GCSD = new CapturaExcelGSD_Verdadero();
        GCSD.setVisible(true);
        this.hide();
        GCSD.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuReportes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GUAMUCHIL;
    private javax.swing.JButton btnAnalisisGente;
    private javax.swing.JButton btnDesgloseCorte;
    private javax.swing.JButton btnDistGente;
    private javax.swing.JButton btnEffort;
    private javax.swing.JButton btnHC;
    private javax.swing.JButton btnRPR;
    private javax.swing.JButton btnRPR1;
    private javax.swing.JButton btnRPR2;
    private javax.swing.JButton btnReporteHC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
