package CapturasEffort;

import Reportes.CeldaCheck;
import Reportes.Render_CheckBox;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import manufactura.Principal;

public class cablesBateria extends javax.swing.JFrame {

    /**
     * Creates new form cablesBateria
     */
    public cablesBateria() {
        try {
            initComponents();
//            Principal.cn=new Conection();
            CargarDgv("TODOS", "TODOS");
            setLocationRelativeTo(null);
        } catch (Exception ex) {
            Logger.getLogger(cablesBateria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void CargarDgv(String Cadena, String Turno) {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"IDCODIGO", "CADENA", "PLATAFORMA", "CODIGO", "LINEA", "TURNO", "CABLE.BATERIA"});
            String query = "SELECT C.IDCODIGO,  c.CADENA, c.PLATAFORMA, c.CODIGO, C.LINEA, C.TURNO, m.BCABLE FROM CODIGOS c, manufactura  m where c.IDCODIGO=m.IDCODIGo and m.ACTIVO=1 ";
            if (!Cadena.equals("TODOS")) {
                query += "and  CADENA='" + Cadena + "' ";
            }
            if (!Turno.equals("TODOS")) {
                query += "AND  Turno='" + Turno + "'";
            }
            ResultSet rs = Principal.cn.GetConsulta(query);
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getBoolean(7)});
            }
            tblConc.setModel(modelo);
            tblConc.getColumnModel().getColumn(0).setMaxWidth(0);
            tblConc.getColumnModel().getColumn(0).setMinWidth(0);
            tblConc.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblConc.getColumnModel().getColumn(6).setCellEditor(new CeldaCheck());
            tblConc.getColumnModel().getColumn(6).setCellRenderer(new Render_CheckBox());
            tblConc.getColumnModel().getColumn(6).setMaxWidth(100);
            tblConc.getColumnModel().getColumn(6).setMinWidth(100);
            tblConc.getColumnModel().getColumn(6).setPreferredWidth(100);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblConc = new Compille.RXTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxCadena = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbxTurno = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblConc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConc.setSelectAllForEdit(true);
        tblConc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConcMouseClicked(evt);
            }
        });
        tblConc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblConcPropertyChange(evt);
            }
        });
        tblConc.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tblConcVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblConc);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("CLASIFICACION DE CODIGOS EN CABLE BATERIA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("CADENA:");

        cbxCadena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxCadena.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "1", "2", "3", "4" }));
        cbxCadena.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCadenaItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("TURNO:");

        cbxTurno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxTurno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "A", "B" }));
        cbxTurno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTurnoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(cbxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(cbxCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblConcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConcMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConcMouseClicked

    private void tblConcPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblConcPropertyChange
        // TODO add your handling code here:
        try {
            if ((tblConc.getSelectedRow() > -1)) {
                ArrayList<Object> lista = new ArrayList<Object>();
                if (tblConc.getValueAt(tblConc.getSelectedRow(), 6).toString().equals("true")) {
                    lista.add(1);
                } else {
                    lista.add(0);
                }
                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 0).toString());
                //lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 0).toString().toUpperCase());
                Principal.cn.EjecutarInsertOb("update manufactura set bcable=?  where idcodigo=?", lista);
                CargarDgv(cbxCadena.getSelectedItem().toString(), cbxTurno.getSelectedItem().toString());

            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_tblConcPropertyChange

    private void tblConcVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tblConcVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConcVetoableChange

    private void cbxCadenaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCadenaItemStateChanged
        // TODO add your handling code here:.
        if ((cbxCadena.getSelectedItem() != null)) {
            CargarDgv(cbxCadena.getSelectedItem().toString(), cbxTurno.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbxCadenaItemStateChanged

    private void cbxTurnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTurnoItemStateChanged
        // TODO add your handling code here:
        if (cbxTurno.getSelectedItem() != null) {
            CargarDgv(cbxCadena.getSelectedItem().toString(), cbxTurno.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbxTurnoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cablesBateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cablesBateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cablesBateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cablesBateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cablesBateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxCadena;
    private javax.swing.JComboBox cbxTurno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private Compille.RXTable tblConc;
    // End of variables declaration//GEN-END:variables

}
