package CapturasEffort;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manufactura.Principal;

public class CapturaPorcentajesEffort extends javax.swing.JFrame {

    /**
     * Creates new form CapturaPorcentajesEffort
     */
    public CapturaPorcentajesEffort() {
        try {
            initComponents();
            //  Principal.cn=new Conection();
            cargarModuloscbxAlta();
            cargarModuloscbxEditar();
            setLocationRelativeTo(null);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

    public void cargarModuloscbxEditar() {
        try {
//        cbxModuloAlta.removeAllItems();
            cbxModulosEditar.removeAllItems();
            ResultSet rs = Principal.cn.GetConsulta("SELECT * FROM MODULOS");
            while (rs.next()) {
//            cbxModuloAlta.addItem(rs.getString(2));
                cbxModulosEditar.addItem(rs.getString(2));
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void cargarModuloscbxAlta() {
        try {
            cbxModuloAlta.removeAllItems();
//        cbxModulosEditar.removeAllItems();
            ResultSet rs = Principal.cn.GetConsulta("SELECT * FROM MODULOS");
            while (rs.next()) {
                cbxModuloAlta.addItem(rs.getString(2));
//            cbxModulosEditar.addItem(rs.getString(2));
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void cargardgv(String Modulo) {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"PLANTA", "MODULO", "PLATAFORMA", "VALOR"});
            ResultSet rs = Principal.cn.GetConsulta("SELECT PLANTA, NOMBREVALOR, PLATAFORMA, VALOR FROM CAPTURAEFFORT WHERE NOMBREVALOR='" + Modulo + "'");
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            tblConc.setModel(modelo);
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxModulosEditar = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConc = new Compille.RXTable();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        txtPlataforma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxModuloAlta = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnAddModulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbxModulosEditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbxModulosEditar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxModulosEditarItemStateChanged(evt);
            }
        });
        cbxModulosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxModulosEditarActionPerformed(evt);
            }
        });

        tblConc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConc.setSelectAllForEdit(true);
        tblConc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConcMouseClicked(evt);
            }
        });
        tblConc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblConcPropertyChange(evt);
            }
        });
        tblConc.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tblConcVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblConc);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Modulo:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/navigate-left48.png"))); // NOI18N
        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/success-icon.png"))); // NOI18N
        btnEntrar.setText("GUARDAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPlataforma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Plataforma:");

        cbxModuloAlta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxModuloAlta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxModuloAltaItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Modulo:");

        btnAddModulo.setText("+");
        btnAddModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddModuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbxModuloAlta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(txtPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEntrar)
                        .addGap(19, 19, 19)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(17, 17, 17)
                        .addComponent(cbxModulosEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxModulosEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxModuloAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblConcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConcMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConcMouseClicked

    private void tblConcPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblConcPropertyChange
        // TODO add your handling code here:
        try {
//            if((tblConc.getSelectedRow()>-1))
//            {
//                ArrayList<Object> lista=new ArrayList<Object>();
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 1).toString());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 2).toString());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 3).toString());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 4).toString());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 5).toString());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 6).toString());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 7).toString());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 8).toString());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 9).toString());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 10).toString());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 11).toString());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 12).toString());
//                //          lista.add(Principal.UsuarioLogeado.nombre);
//                lista.add(1);
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 0).toString());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 13).toString());
//                Principal.cn.EjecutarInsertOb("update concentradoeffort set enero=?, febrero=?, marzo=?, abril=?, mayo=?, junio=?, julio=?, agosto=?, septiembre=?, octubre=?, noviembre=?, diciembre=?, usuariomodifico=?, fechamodifico=now() where nombre=? and ano=? ", lista);
//            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_tblConcPropertyChange

    private void tblConcVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tblConcVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConcVetoableChange

    private void btnAddModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddModuloActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("AGREGAR NUEVO MODULO CAPTURA");
        String NombreModulo = "";
        NombreModulo = JOptionPane.showInputDialog(frame, "NOMBRE MODULO?");
        if (NombreModulo != null) {
            try {
                NombreModulo = NombreModulo.toUpperCase();
                ResultSet rs = Principal.cn.GetConsulta("SELECT * FROM modulos where modulo='" + NombreModulo + "'");
                if (rs.next() && rs.isFirst()) {
                    JOptionPane.showMessageDialog(null, "MODULO YA ESTA DADO DE ALTA", "", JOptionPane.WARNING_MESSAGE);
                } else {
                    ArrayList<String> lista = new ArrayList<String>();
                    lista.add(NombreModulo);
                    if (Principal.cn.EjecutarInsert("INSERT INTO MODULOS (MODULO) VALUES (?)", lista)) {
                        cargarModuloscbxAlta();
                        cargarModuloscbxEditar();
                    }
                }
            } catch (SQLException ex) {
                System.out.println(ex.toString());

            }
        }
    }//GEN-LAST:event_btnAddModuloActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
//      if((cbxModuloAlta.getSelectedItem()!=null) || )
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:\
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxModulosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxModulosEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxModulosEditarActionPerformed

    private void cbxModulosEditarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxModulosEditarItemStateChanged
        // TODO add your handling code here:
        if (cbxModulosEditar.getSelectedItem() != null) {
            cargardgv(cbxModulosEditar.getSelectedItem().toString());
            cargarModuloscbxAlta();
        }


    }//GEN-LAST:event_cbxModulosEditarItemStateChanged

    private void cbxModuloAltaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxModuloAltaItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxModuloAltaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapturaPorcentajesEffort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapturaPorcentajesEffort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapturaPorcentajesEffort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapturaPorcentajesEffort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapturaPorcentajesEffort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddModulo;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JComboBox cbxModuloAlta;
    private javax.swing.JComboBox cbxModulosEditar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private Compille.RXTable tblConc;
    private javax.swing.JTextField txtPlataforma;
    // End of variables declaration//GEN-END:variables
}
