
package CapturasEffort;

import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import manufactura.Principal;

public class clasificacionPlataforma extends javax.swing.JFrame {

    /**
     * Creates new form clasificacionPlataforma
     */
    public clasificacionPlataforma() {
        try {
            initComponents();
            setLocationRelativeTo(null);
//            Principal.cn=new Conection();
            enlazartablaDisp("TODOS", "TODOS");
            EnlazarTablaClasificacion("25962");

        } catch (Exception ex) {
            Logger.getLogger(clasificacionPlataforma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void enlazartablaDisp(String Cadena, String Turno) {
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"IDCODIGO", "CADENA", "CODIGO", "LINEA", "TURNO"});
            String query = "SELECT IDCODIGO, CADENA, CODIGO, LINEA, TURNO FROM CODIGOS where DEPTO is NULL and cadena<>7  and codigo<>'SERV  ' ";
            if (!Cadena.equals("TODOS")) {
                query += "and  CADENA='" + Cadena + "' ";
            }
            if (!Turno.equals("TODOS")) {
                query += "AND  Turno='" + Turno + "'";
            }
            query += " order by cadena asc";
            ResultSet rs = Principal.cn.GetConsulta(query);
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            tblConc.setModel(modelo);
            tblConc.getColumnModel().getColumn(0).setMaxWidth(0);
            tblConc.getColumnModel().getColumn(0).setMinWidth(0);
            tblConc.getColumnModel().getColumn(0).setPreferredWidth(0);
        } catch (Exception e) {

        }
    }

    public void EnlazarTablaClasificacion(String Depto) {
        try {
            DefaultTableModel modelo = new DefaultTableModel() {

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;//To change body of generated methods, choose Tools | Templates.
                }

            };
            modelo.setColumnIdentifiers(new Object[]{"IDCODIGO", "CADENA", "CODIGO", "LINEA", "TURNO"});

            ResultSet rs = Principal.cn.GetConsulta("SELECT IDCODIGO, CADENA, CODIGO, LINEA, TURNO FROM CODIGOS where DEPTO='" + Depto + "' and cadena<>7  and codigo<>'SERV' order by cadena asc ");
//              query+=" ";
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            tblConc1.setModel(modelo);
            tblConc1.getColumnModel().getColumn(0).setMaxWidth(0);
            tblConc1.getColumnModel().getColumn(0).setMinWidth(0);
            tblConc1.getColumnModel().getColumn(0).setPreferredWidth(0);
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblConc = new Compille.RXTable();
        jLabel1 = new javax.swing.JLabel();
        cbxDepto = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConc1 = new Compille.RXTable();
        btnEnviarUno = new javax.swing.JButton();
        btnEnviarTodos = new javax.swing.JButton();
        btnRegTodos = new javax.swing.JButton();
        btnRegUno = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbxCadena = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbxTurno = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblConc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConc.setSelectAllForEdit(true);
        tblConc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConcMouseClicked(evt);
            }
        });
        tblConc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblConcPropertyChange(evt);
            }
        });
        tblConc.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tblConcVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblConc);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DEPARTAMENTO:");

        cbxDepto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cbxDepto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "25962", "25963" }));
        cbxDepto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDeptoItemStateChanged(evt);
            }
        });
        cbxDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDeptoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("CLASIFICACION DE CODIGOS EN DEPTO");

        tblConc1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConc1.setSelectAllForEdit(true);
        tblConc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConc1MouseClicked(evt);
            }
        });
        tblConc1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblConc1PropertyChange(evt);
            }
        });
        tblConc1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tblConc1VetoableChange(evt);
            }
        });
        jScrollPane2.setViewportView(tblConc1);

        btnEnviarUno.setText(">");
        btnEnviarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarUnoActionPerformed(evt);
            }
        });

        btnEnviarTodos.setText(">>");
        btnEnviarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarTodosActionPerformed(evt);
            }
        });

        btnRegTodos.setText("<<");
        btnRegTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegTodosActionPerformed(evt);
            }
        });

        btnRegUno.setText("<");
        btnRegUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegUnoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("CADENA:");

        cbxCadena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxCadena.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "1", "2", "3", "4" }));
        cbxCadena.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCadenaItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("TURNO:");

        cbxTurno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxTurno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "A", "B" }));
        cbxTurno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTurnoItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("CODIGOS DISP. ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEnviarUno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEnviarTodos)
                                    .addComponent(btnRegUno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRegTodos))
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(cbxDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)))
                    .addComponent(cbxDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(cbxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(cbxCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnEnviarUno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnEnviarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnRegUno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnRegTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblConcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConcMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConcMouseClicked

    private void tblConcPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblConcPropertyChange
        // TODO add your handling code here:
        try {
            if ((tblConc.getSelectedRow() > -1)) {
//                ArrayList<Object> lista=new ArrayList<Object>();
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 1).toString().toUpperCase());
//                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 0).toString().toUpperCase());
//                Principal.cn.EjecutarInsertOb("update departamentos set descripcion=?  where id_depto=?", lista);
//                cargardepto();

            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_tblConcPropertyChange

    private void tblConcVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tblConcVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConcVetoableChange

    private void tblConc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConc1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConc1MouseClicked

    private void tblConc1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblConc1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConc1PropertyChange

    private void tblConc1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tblConc1VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConc1VetoableChange

    private void cbxCadenaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCadenaItemStateChanged
        // TODO add your handling code here:.
        if ((cbxCadena.getSelectedItem() != null)) {
            enlazartablaDisp(cbxCadena.getSelectedItem().toString(), cbxTurno.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbxCadenaItemStateChanged

    private void cbxTurnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTurnoItemStateChanged
        // TODO add your handling code here:
        if (cbxTurno.getSelectedItem() != null) {
            enlazartablaDisp(cbxCadena.getSelectedItem().toString(), cbxTurno.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbxTurnoItemStateChanged

    private void cbxDeptoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDeptoItemStateChanged
        // TODO add your handling code here:
        if (cbxDepto.getSelectedItem() != null) {
            EnlazarTablaClasificacion(cbxDepto.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbxDeptoItemStateChanged

    private void btnEnviarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarUnoActionPerformed
        // TODO add your handling code here:
        if (tblConc.getSelectedRow() > -1) {
            String idcodigo = tblConc.getModel().getValueAt(tblConc.getSelectedRow(), 0).toString();
            ArrayList<String> lista = new ArrayList<String>();
            lista.add(cbxDepto.getSelectedItem().toString());
            lista.add(idcodigo);
            Principal.cn.EjecutarInsert("UPDATE CODIGOS SET DEPTO=? WHERE IDCODIGO=?", lista);
            EnlazarTablaClasificacion(cbxDepto.getSelectedItem().toString());
            enlazartablaDisp(cbxCadena.getSelectedItem().toString(), cbxTurno.getSelectedItem().toString());
        }
    }//GEN-LAST:event_btnEnviarUnoActionPerformed

    private void btnEnviarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarTodosActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < tblConc.getModel().getRowCount(); i++) {
            String idcodigo = tblConc.getModel().getValueAt(i, 0).toString();
            ArrayList<String> lista = new ArrayList<String>();
            lista.add(cbxDepto.getSelectedItem().toString());
            lista.add(idcodigo);
            Principal.cn.EjecutarInsert("UPDATE CODIGOS SET DEPTO=? WHERE IDCODIGO=?", lista);

        }
        EnlazarTablaClasificacion(cbxDepto.getSelectedItem().toString());
        enlazartablaDisp(cbxCadena.getSelectedItem().toString(), cbxTurno.getSelectedItem().toString());
    }//GEN-LAST:event_btnEnviarTodosActionPerformed

    private void btnRegUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegUnoActionPerformed
        // TODO add your handling code here:
        if (tblConc1.getSelectedRow() > -1) {
            String idcodigo = tblConc1.getModel().getValueAt(tblConc1.getSelectedRow(), 0).toString();
            ArrayList<String> lista = new ArrayList<String>();
//            lista.add(cbxDepto.getSelectedItem().toString());
            lista.add(idcodigo);
            Principal.cn.EjecutarInsert("UPDATE CODIGOS SET DEPTO=Null WHERE IDCODIGO=?", lista);
            EnlazarTablaClasificacion(cbxDepto.getSelectedItem().toString());
            enlazartablaDisp(cbxCadena.getSelectedItem().toString(), cbxTurno.getSelectedItem().toString());
        }
    }//GEN-LAST:event_btnRegUnoActionPerformed

    private void btnRegTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegTodosActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < tblConc1.getModel().getRowCount(); i++) {
            String idcodigo = tblConc1.getModel().getValueAt(i, 0).toString();
            ArrayList<String> lista = new ArrayList<String>();
//            lista.add(cbxDepto.getSelectedItem().toString());
            lista.add(idcodigo);
            Principal.cn.EjecutarInsert("UPDATE CODIGOS SET DEPTO=Null WHERE IDCODIGO=?", lista);
        }
        EnlazarTablaClasificacion(cbxDepto.getSelectedItem().toString());
        enlazartablaDisp(cbxCadena.getSelectedItem().toString(), cbxTurno.getSelectedItem().toString());
    }//GEN-LAST:event_btnRegTodosActionPerformed

    private void cbxDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDeptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clasificacionPlataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clasificacionPlataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clasificacionPlataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clasificacionPlataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clasificacionPlataforma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarTodos;
    private javax.swing.JButton btnEnviarUno;
    private javax.swing.JButton btnRegTodos;
    private javax.swing.JButton btnRegUno;
    private javax.swing.JComboBox cbxCadena;
    private javax.swing.JComboBox cbxDepto;
    private javax.swing.JComboBox cbxTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private Compille.RXTable tblConc;
    private Compille.RXTable tblConc1;
    // End of variables declaration//GEN-END:variables

}
