package CapturasEffort;

import Reportes.MenuReportes;

public class MenuEffort extends javax.swing.JFrame {

    /**
     * Creates new form MenuEffort
     */
    public MenuEffort() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCapturaScrap = new javax.swing.JButton();
        btnCapturaDepto = new javax.swing.JButton();
        btnCapturaHC = new javax.swing.JButton();
        btnCapturas3 = new javax.swing.JButton();
        btnCapturas4 = new javax.swing.JButton();
        btnCapturas6 = new javax.swing.JButton();
        btnCapturas7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MENU DE EFFORT");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnCapturaScrap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit-Document-icon (1).png"))); // NOI18N
        btnCapturaScrap.setText("SCRAP, SQ.FT. TLO");
        btnCapturaScrap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapturaScrap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCapturaScrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturaScrapActionPerformed(evt);
            }
        });

        btnCapturaDepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Folders-OS-Groups-Metro-icon.png"))); // NOI18N
        btnCapturaDepto.setText("CLASIFICACION LINEA EN DEPTO");
        btnCapturaDepto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapturaDepto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCapturaDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturaDeptoActionPerformed(evt);
            }
        });

        btnCapturaHC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/groups-icon.png"))); // NOI18N
        btnCapturaHC.setText("HEAD COUNT RH");
        btnCapturaHC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapturaHC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCapturaHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturaHCActionPerformed(evt);
            }
        });

        btnCapturas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Folder-Public-icon.png"))); // NOI18N
        btnCapturas3.setText("DEPARTAMENTOS");
        btnCapturas3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapturas3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCapturas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturas3ActionPerformed(evt);
            }
        });

        btnCapturas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pencil-holder-icon.png"))); // NOI18N
        btnCapturas4.setText("CABLE BATERIA");
        btnCapturas4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapturas4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCapturas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturas4ActionPerformed(evt);
            }
        });

        btnCapturas6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Apps-Gazebo-icon.png"))); // NOI18N
        btnCapturas6.setText("PORCENTAJES");
        btnCapturas6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapturas6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCapturas6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturas6ActionPerformed(evt);
            }
        });

        btnCapturas7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Apps-2048-icon.png"))); // NOI18N
        btnCapturas7.setText("GENERAR REPORT EFFORT");
        btnCapturas7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapturas7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCapturas7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturas7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("LOS MOCHIS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCapturaDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnCapturas4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCapturaScrap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnCapturas3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCapturaHC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnCapturas6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCapturas7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(183, 183, 183))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCapturaScrap, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnCapturas3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCapturaDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapturas4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCapturaHC, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapturas6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCapturas7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapturaScrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturaScrapActionPerformed
        // TODO add your handling code here:
        CapturaTotales cp = new CapturaTotales();
        cp.setVisible(true);
    }//GEN-LAST:event_btnCapturaScrapActionPerformed

    private void btnCapturaDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturaDeptoActionPerformed
        // TODO add your handling code here:
        clasificacionPlataforma cL = new clasificacionPlataforma();
        cL.setVisible(true);
    }//GEN-LAST:event_btnCapturaDeptoActionPerformed

    private void btnCapturaHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturaHCActionPerformed
        // TODO add your handling code here:
        CapturaHCR hc = new CapturaHCR();
        hc.setVisible(true);
    }//GEN-LAST:event_btnCapturaHCActionPerformed

    private void btnCapturas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturas3ActionPerformed
        // TODO add your handling code here:c
        CapturaDepto dt = new CapturaDepto();
        dt.setVisible(true);
    }//GEN-LAST:event_btnCapturas3ActionPerformed

    private void btnCapturas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturas4ActionPerformed
        // TODO add your handling code here:ble
        cablesBateria cb = new cablesBateria();
        cb.setVisible(true);
    }//GEN-LAST:event_btnCapturas4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Reportes.MenuReportes menu = new MenuReportes();
        menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnCapturas6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturas6ActionPerformed
        // TODO add your handling code here:
        CapturaPorcentajes p = new CapturaPorcentajes();
        p.setVisible(true);
    }//GEN-LAST:event_btnCapturas6ActionPerformed

    private void btnCapturas7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturas7ActionPerformed
        // TODO add your handling code here:

        PorcentajesHC p = new PorcentajesHC();
        p.setVisible(true);
    }//GEN-LAST:event_btnCapturas7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEffort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEffort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEffort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEffort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEffort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturaDepto;
    private javax.swing.JButton btnCapturaHC;
    private javax.swing.JButton btnCapturaScrap;
    private javax.swing.JButton btnCapturas3;
    private javax.swing.JButton btnCapturas4;
    private javax.swing.JButton btnCapturas6;
    private javax.swing.JButton btnCapturas7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
