/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package effortGUA;

import java.awt.Point;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manufactura.Principal;


public class CapturaDepto2 extends javax.swing.JFrame {

    /**
     * Creates new form CapturaDepto2
     */
    public CapturaDepto2() {
       
            initComponents();
//            Principal.cn=new Conection();
            txtClave.requestFocus();
            setLocationRelativeTo(null);
            cargardepto();
        
    }

    public  void cargardepto()
    {
        try
        {
            DefaultTableModel modelo=new DefaultTableModel()
            {
                @Override
                public boolean isCellEditable(int row, int column) {
                    if(column==0)
                        return false;
                    else
                       return true;     
//To change body of generated methods, choose Tools | Templates.
                }
            
            };
            modelo.setColumnIdentifiers(new Object[]{"CLAVE", "DEPTO"});
            ResultSet rs=Principal.cn.GetConsulta("SELECT * FROM departamentos_GUA");
            while(rs.next())
            {
            modelo.addRow(new Object[]{rs.getString(1), rs.getString(2)});
            }
            tblConc.setModel(modelo);
        } catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConc = new Compille.RXTable();
        jLabel17 = new javax.swing.JLabel();
        txtDepto = new javax.swing.JTextField();
        GUAMUCHIL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CAPTURA DEPARMENTOS\n");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/success-icon.png"))); // NOI18N
        btnEntrar.setText("GUARDAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/navigate-left48.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("CLAVE:");

        txtClave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblConc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConc.setSelectAllForEdit(true);
        tblConc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConcMouseClicked(evt);
            }
        });
        tblConc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblConcPropertyChange(evt);
            }
        });
        tblConc.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tblConcVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblConc);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Departamento:");

        txtDepto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        GUAMUCHIL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        GUAMUCHIL.setText("GUAMUCHIL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEntrar)
                                .addGap(6, 6, 6)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GUAMUCHIL)
                        .addGap(70, 70, 70)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GUAMUCHIL)
                .addGap(39, 39, 39)
                .addComponent(jLabel16)
                .addGap(11, 11, 11)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(11, 11, 11)
                .addComponent(txtDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        ArrayList<String> lista=new  ArrayList<String>();
        lista.add(txtClave.getText().toUpperCase());
        lista.add(txtDepto.getText().toUpperCase());
        if(Principal.cn.EjecutarInsert("INSERT INTO departamentos_GUA (ID_DEPTO, DESCRIPCION) VALUES (?, ?)", lista))
        {
            cargardepto();
            txtClave.setText("");
            txtDepto.setText("");
            txtClave.requestFocus();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error al guardar, consulte asu administrador", "ERROR", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:\
        this.dispose();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblConcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConcMouseClicked
        // TODO add your handling code here:
        Point point = evt.getPoint();
        int row = tblConc.rowAtPoint(point);
        if (evt.getClickCount() == 2) {
            int reply = JOptionPane.showConfirmDialog(null, "Desea eliminar el departamento "+tblConc.getModel().getValueAt(row, 1).toString()+" ?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION)
                  {
                      ArrayList<String> lista=new  ArrayList<String>();
                     Principal.cn.EjecutarInsert("DELETE   FROM departamentos_GUA WHERE ID_DEPTO="+tblConc.getModel().getValueAt(row, 0).toString(), lista);
                     cargardepto();
                }
   
}
    }//GEN-LAST:event_tblConcMouseClicked

    private void tblConcPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblConcPropertyChange
        // TODO add your handling code here:
        try{
                        if((tblConc.getSelectedRow()>-1))
                        {
                                ArrayList<Object> lista=new ArrayList<Object>();
                                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 1).toString().toUpperCase());
                                lista.add(tblConc.getValueAt(tblConc.getSelectedRow(), 0).toString().toUpperCase());
                                Principal.cn.EjecutarInsertOb("update departamentos_GUA set descripcion=?  where id_depto=?", lista);
                                    cargardepto();
                                
                          }
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_tblConcPropertyChange

    private void tblConcVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tblConcVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConcVetoableChange

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapturaDepto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapturaDepto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapturaDepto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapturaDepto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapturaDepto2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GUAMUCHIL;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private Compille.RXTable tblConc;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtDepto;
    // End of variables declaration//GEN-END:variables
}
