/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package effortGUA;

import Clases.Conection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import manufactura.Principal;



public class CapturaPorcentajes2 extends javax.swing.JFrame {

    /**
     * Creates new form CapturaPorcentajes2
     */
    public CapturaPorcentajes2() {
        try {
            initComponents();
            Principal.cn=new Conection();
            setLocationRelativeTo(null);
            cargardgv();
        } catch (Exception ex) {
            Logger.getLogger(CapturaPorcentajes2.class.getName()).log(Level.SEVERE, null, ex);
        } 
    
    }
    
    public void cargardgv(){
        try{
            ResultSet rs=Principal.cn.GetConsulta("select distinct modulo from porcentajes_GUA");
            while(rs.next())
            {
                cbxModulos.addItem(rs.getString(1));         
            }
        }catch(Exception e)
        {
        
        }
    }
   
    public void obtenerPorcentajes(String Modulo){
        try{
            ResultSet rs=Principal.cn.GetConsulta("select * from porcentajes_GUA where modulo='"+Modulo+"'");
            if(rs.next())
            {
                txtBcable.setValue(rs.getDouble("BCABLE"));
                txtCamaro.setValue(rs.getDouble("GMX521"));
                txtGmt610.setValue(rs.getDouble("GMT610"));
                txtIsuzu.setValue(rs.getDouble("ISUZU_"));
                txtK2xx.setValue(rs.getDouble("K2XX"));
                txtServicios.setValue(rs.getDouble("SERVICIOS"));
            }
        }catch(Exception e)
        {
            
        }
    }
  
    public void sacarTotales(){
        Double Total=0.0;
        try{
            Total=(Double)txtGmt610.getValue()+(Double)txtCamaro.getValue()+(Double)txtBcable.getValue()+(Double)txtIsuzu.getValue()+(Double)txtK2xx.getValue()+(Double)txtServicios.getValue();
            txtTotal.setText(Total.toString());
                    
        }catch(Exception e)
        {
           System.out.println(e.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbxModulos = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtBcable = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        txtGmt610 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txtCamaro = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtIsuzu = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtK2xx = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtServicios = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        pnlMenu.setBackground(new java.awt.Color(255, 255, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Captura Porcentajes EFFORT");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cbxModulos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbxModulos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxModulosItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Modulo:");

        txtBcable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtBcable.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        txtBcable.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtBcableStateChanged(evt);
            }
        });
        txtBcable.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtBcableVetoableChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("BCABLE:");

        txtGmt610.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtGmt610.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        txtGmt610.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtGmt610StateChanged(evt);
            }
        });
        txtGmt610.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtGmt610VetoableChange(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("GMT 610:");

        txtCamaro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCamaro.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        txtCamaro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCamaroStateChanged(evt);
            }
        });
        txtCamaro.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtCamaroVetoableChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("GMX-521:");

        txtIsuzu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtIsuzu.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        txtIsuzu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtIsuzuStateChanged(evt);
            }
        });
        txtIsuzu.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtIsuzuVetoableChange(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("ISUZU:");

        txtK2xx.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtK2xx.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        txtK2xx.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtK2xxStateChanged(evt);
            }
        });
        txtK2xx.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtK2xxVetoableChange(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("K2XX:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("SERVICIOS:");

        txtServicios.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtServicios.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));
        txtServicios.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtServiciosStateChanged(evt);
            }
        });
        txtServicios.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtServiciosVetoableChange(evt);
            }
        });

        jLabel9.setText("_____________________________________");

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("TOTAL:");

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/success-icon.png"))); // NOI18N
        btnEntrar.setText("GUARDAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/navigate-left48.png"))); // NOI18N
        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBcable, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGmt610, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCamaro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIsuzu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtK2xx, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel9)))
                .addGap(193, 193, 193))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbxModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEntrar)
                                .addGap(19, 19, 19)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBcable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGmt610, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCamaro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIsuzu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtK2xx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        //      if((cbxModuloAlta.getSelectedItem()!=null) || )
        if(Double.parseDouble(txtTotal.getText())==100)
        {
            ArrayList<Object> lista=new ArrayList<Object>();
            lista.add(txtBcable.getValue());
            lista.add(txtGmt610.getValue());
            lista.add(txtCamaro.getValue());
            lista.add(txtIsuzu.getValue());
            lista.add(txtK2xx.getValue());
            lista.add(txtServicios.getValue()); 
            lista.add(cbxModulos.getSelectedItem());
//lista.add(txtIsuzu.getValue());
            Principal.cn.EjecutarInsertOb("UPDATE porcentajes_GUA  SET BCABLE=?, GMT610=?, GMX521=?, ISUZU_=?, K2XX=?, SERVICIOS=? WHERE MODULO=?", lista);
            JOptionPane.showMessageDialog(null, "DATOS ACTUALIZADOS...", "", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "ERROR, LA SUMA EN PORCENTAJE  NO ES IGUAL 100% ...", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:\
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBcableVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtBcableVetoableChange
        // TODO add your handling code here:
//        if(Double.parseDouble(txtBcable.getValue().toString())>0)
         sacarTotales();
    }//GEN-LAST:event_txtBcableVetoableChange

    private void txtGmt610VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtGmt610VetoableChange
        // TODO add your handling code here:
//        if(Double.parseDouble(txtGmt610.getValue().toString())>0)
         sacarTotales();
    }//GEN-LAST:event_txtGmt610VetoableChange

    private void txtCamaroVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtCamaroVetoableChange
        // TODO add your handling code here:
//        if(Double.parseDouble(txtCamaro.getValue().toString())>0)
         sacarTotales();
    }//GEN-LAST:event_txtCamaroVetoableChange

    private void txtIsuzuVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtIsuzuVetoableChange
        // TODO add your handling code here:
        if(Double.parseDouble(txtIsuzu.getValue().toString())>0)
         sacarTotales();
    }//GEN-LAST:event_txtIsuzuVetoableChange

    private void txtK2xxVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtK2xxVetoableChange
        // TODO add your handling code here:
//         if(Double.parseDouble(txtK2xx.getValue().toString())>0)
         sacarTotales();
    }//GEN-LAST:event_txtK2xxVetoableChange

    private void txtServiciosVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtServiciosVetoableChange
        // TODO add your handling code here:
//          if(Double.parseDouble(txtServicios.getValue().toString())>0)
            sacarTotales();
    }//GEN-LAST:event_txtServiciosVetoableChange

    private void txtBcableStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtBcableStateChanged
        // TODO add your handling code here:
        sacarTotales();
    }//GEN-LAST:event_txtBcableStateChanged

    private void txtGmt610StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtGmt610StateChanged
        // TODO add your handling code here:
        sacarTotales();
    }//GEN-LAST:event_txtGmt610StateChanged

    private void txtCamaroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCamaroStateChanged
        // TODO add your handling code here:
        sacarTotales();
    }//GEN-LAST:event_txtCamaroStateChanged

    private void txtIsuzuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtIsuzuStateChanged
        // TODO add your handling code here:
        sacarTotales();
    }//GEN-LAST:event_txtIsuzuStateChanged

    private void txtK2xxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtK2xxStateChanged
        // TODO add your handling code here:
        sacarTotales();
    }//GEN-LAST:event_txtK2xxStateChanged

    private void txtServiciosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtServiciosStateChanged
        // TODO add your handling code here:
        sacarTotales();
    }//GEN-LAST:event_txtServiciosStateChanged

    private void cbxModulosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxModulosItemStateChanged
        // TODO add your handling code here:
        if(cbxModulos.getSelectedItem()!=null)
        {
            obtenerPorcentajes(cbxModulos.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbxModulosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapturaPorcentajes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapturaPorcentajes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapturaPorcentajes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapturaPorcentajes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapturaPorcentajes2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JComboBox cbxModulos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JSpinner txtBcable;
    private javax.swing.JSpinner txtCamaro;
    private javax.swing.JSpinner txtGmt610;
    private javax.swing.JSpinner txtIsuzu;
    private javax.swing.JSpinner txtK2xx;
    private javax.swing.JSpinner txtServicios;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
